config/routes.rb
Rails.application.routes.draw do
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy"
  post "/cats", to: "cats#create"
  delete "/cats", to: "cats#destroy"
  get "/agency/:id/cats", to: "agencies#cats_by_agency"
  get '/auth/facebook/callback' => 'sessions#create'

  resources :cats

  resources :agencies do
    resources :cats, only: [:show, :index, :cats_by_agency]
  end

  resources :users

  root "welcome#home"
end

app/models/agency.rb
class Agency < ApplicationRecord
  has_many :cats
  has_many :users, through: :cats

  validates :name, :state, :email, presence: :true
  validates :phone_number, length: {is: 10}


  include EmailValidatable
  validates :email, uniqueness: true
  validates :email, email: true

  def agency_name
    self.find(params[:id]).name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :agency
  belongs_to :user

  validates :name, :breed, :disposition, :age, :sex, :agency_id, presence: :true

  def adopted?
    self.adopted == true
  end

  def neutered?
    if self.neutered == true
      "Yes"
    else
      "No"
    end
  end

end

app/models/concerns/email_validatable.rb
require 'mail'

module EmailValidatable
  extend ActiveSupport::Concern

  class EmailValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      begin
        a = Mail::Address.new(value)
      rescue Mail::Field::ParseError
        record.errors[attribute] << (options[:message] || "isn't a valid email")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, :money, :email, presence: true

  include EmailValidatable
  validates :email, uniqueness: true
  validates :email, email: true

  has_many :cats
  has_many :agencies, through: :cats

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  def new
    @agency = Agency.new
  end

  def create
    @agency = Agency.new(agency_params)
     if @agency.save
       redirect_to agency_path(@agency)
     else
       render :new
     end
  end

  def show
    @agency = Agency.find(params[:id])
  end

  def edit
    @agency = Agency.find_by_id(params[:id])
  end

  def index
    @agencies = Agency.all
  end

  def update
    @agency = Agency.find_by_id(params[:id])
    if @agency.update(agency_params)
      redirect_to @agency
    else
      render :edit
    end
  end

  private
  def agency_params
   params.require(:agency).permit(:name, :street_1, :street_2, :zip_code, :city, :state, :email, :phone_number)
  end


end

app/controllers/agency_controller.rb
class AgenciesController < ApplicationController
  def new
    @agency = Agency.new
  end

  def create
    @agency = Agency.new(agency_params)
     if @agency.save
       redirect_to agency_path(@agency)
     else
       render :new
     end
  end

  def show
    @agency = Agency.find_by_id(params[:id])
  end

  private
  def agency_params
   params.require(:agency).permit(:name, :street_1, :street_2, :zip_code, :state, :email, :phone_number)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :require_logged_in
  helper_method :current_user, :logged_in?, :admin?

  def logged_in?
    session[:user_id]
  end

  def require_logged_in
    redirect_to root_path unless logged_in?
  end

  def redirect_to_current_user
    @user = User.find_by_id(session[:user_id])
      redirect_to user_path(@user)
    end


  def current_user
    @user = User.find_by_id(session[:user_id])
  end

  def admin?
    current_user.admin if logged_in?
  end

  def user_name
    current_user.name
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    if @agency = Agency.find_by_id(params["agency_id"])
      @cats = @agency.cats
    else
    @cats = Cat.all
  end
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
     if @cat.save
       redirect_to cat_path(@cat)
     else
       render :new
     end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def edit
    @cat = Cat.find_by_id(params[:id])
  end

  def update
    @cat = Cat.find_by_id(params[:id])
    if @cat.update(cat_params)
      redirect_to @cat
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find_by_id(params[:id])
      @cat.destroy
      redirect_to cats_path
  end

  private


  def cat_params
   params.require(:cat).permit(:name, :age, :breed, :sex, :disposition, :cost, :adopted, :neutered, :image, :agency_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_logged_in, only: [:new, :create]

  def new
  end

  def create
    if
      user = User.find_by(email: params[:user][:email])
      user = user.try(:authenticate, params[:user][:password])
      return redirect_to(controller: 'sessions', action: 'new') unless user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private
  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_logged_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
     if @user.save
       session[:user_id] = @user.id
       redirect_to user_path(@user)
     else
       render :new
     end
  end

  def show
  end

  def edit
  end

  def update
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit
      end
    end

  private


  def user_params
   params.require(:user).permit(:name, :password, :email, :money, :admin)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_logged_in

  def home
    if current_user != nil
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/agency_helper.rb
module AgencyHelper
  def us_states
        [
          ['Alabama', 'AL'],
          ['Alaska', 'AK'],
          ['Arizona', 'AZ'],
          ['Arkansas', 'AR'],
          ['California', 'CA'],
          ['Colorado', 'CO'],
          ['Connecticut', 'CT'],
          ['Delaware', 'DE'],
          ['District of Columbia', 'DC'],
          ['Florida', 'FL'],
          ['Georgia', 'GA'],
          ['Hawaii', 'HI'],
          ['Idaho', 'ID'],
          ['Illinois', 'IL'],
          ['Indiana', 'IN'],
          ['Iowa', 'IA'],
          ['Kansas', 'KS'],
          ['Kentucky', 'KY'],
          ['Louisiana', 'LA'],
          ['Maine', 'ME'],
          ['Maryland', 'MD'],
          ['Massachusetts', 'MA'],
          ['Michigan', 'MI'],
          ['Minnesota', 'MN'],
          ['Mississippi', 'MS'],
          ['Missouri', 'MO'],
          ['Montana', 'MT'],
          ['Nebraska', 'NE'],
          ['Nevada', 'NV'],
          ['New Hampshire', 'NH'],
          ['New Jersey', 'NJ'],
          ['New Mexico', 'NM'],
          ['New York', 'NY'],
          ['North Carolina', 'NC'],
          ['North Dakota', 'ND'],
          ['Ohio', 'OH'],
          ['Oklahoma', 'OK'],
          ['Oregon', 'OR'],
          ['Pennsylvania', 'PA'],
          ['Puerto Rico', 'PR'],
          ['Rhode Island', 'RI'],
          ['South Carolina', 'SC'],
          ['South Dakota', 'SD'],
          ['Tennessee', 'TN'],
          ['Texas', 'TX'],
          ['Utah', 'UT'],
          ['Vermont', 'VT'],
          ['Virginia', 'VA'],
          ['Washington', 'WA'],
          ['West Virginia', 'WV'],
          ['Wisconsin', 'WI'],
          ['Wyoming', 'WY']
        ]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agencies/_form.html.erb
<%= form_for @agency do |f|%>

<%=f.label 'name'%>: <br>
<%=f.text_field :name %> <br>
<br>
<%=f.label 'street_1'%>: <br>
<%=f.text_field :street_1 %> <br>
<br>
<%=f.label 'street_2'%>: <br>
<%=f.text_field :street_2 %> <br>
<br>
<%=f.label 'city'%>: <br>
<%=f.text_field :city %> <br>
<br>
<%=f.label 'state'%>: <br>
<%= f.select :state, options_for_select(us_states) %> <br>
<br>
<%= f.label 'zip_code', 'Zip Code' %>:<br>
<%= f.text_field :zip_code%><br>
<br>
<%= f.label 'email' %>:<br>
<%= f.text_field :email%><br>
<br>
<%=f.label 'phone_number', 'Phone Number'%>:  <br>
<%=f.text_field :phone_number %> <br>
<br>
<%= f.submit "Submit" %>
<%end%>

<br>

app/views/agencies/edit.html.erb
<% if @agency.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@agency.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @agency.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= render 'form'%>

<%= link_to 'Back', agency_path(@agency) %>

app/views/agencies/index.html.erb
<h1>All Cat Adoption Agencies</h1>

<%@agencies.each do |a|%>
<ul>
  <%= link_to a.name, agency_path(a)%> - <%=a.state%>
</ul>
<%end%>

<%if current_user.admin?%>
  <%=link_to "New Agency", new_agency_path%>
  <%end%>

app/views/agencies/new.html.erb
<h1>Create a New Adoption Agency</h1>

<%= render "form"%>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<h1><%= @agency.name %></h1>
<h4><%= @agency.email%></h4>
<h4><%= number_to_phone(@agency.phone_number)%></h4>

<p>
  <%=@agency.street_1%><br>
  <%=@agency.street_2%>
  <%=@agency.city%>
  <%=@agency.state%>
  <%=@agency.zip_code%>
</p>
<%= link_to "Cats at this Agency", agency_cats_path(@agency.id)%>

<%if current_user.admin?%>
<%= link_to "Add Cat", new_cat_path%>
<%= link_to 'Edit', edit_agency_path(@agency)%>
<%end%>
<br>
<br>

app/views/cats/_form.html.erb
<%= form_for @cat do |f|%>

<%=f.label 'name'%>: <br>
<%=f.text_field :name %> <br>
<br>
<%=f.label 'breed'%>: <br>
<%=f.text_field :breed %> <br>
<br>
<%=f.label 'age'%>: <br>
<%=f.text_field :age %> <br>
<br>
<%=f.label 'sex'%>: <br>
<%= f.select :sex, [["Male", "Male"], ["Female", "Female"], ["Unknown", "Unknown"]], {}, {class: "form-control"} %><br>
<br>
<%= f.label :disposition %>:<br>
<%= f.text_field :disposition%><br>
<br>
<%= f.label :cost, "Cost to Adopt" %>:<br>
$<%= f.text_field :cost%><br>
<br>
<%= f.label :neutered, "Spayed/Neutered?" %><br>
<%= f.check_box :neutered%> Yes <br>
<br>
<%=f.label 'image', "Image Link"%>: <br>
<%=f.text_field :image %> <br>
<br>
<%= f.label :agency_id, "Adoption Agency"%>: <br>
<%= f.collection_select(:agency_id, Agency.all, :id, :name) %><br>
<br>
<%= f.submit "Submit" %>
<%end%>

<br>

app/views/cats/edit.html.erb
<h1>Edit Cat</h1>
<%=render 'form'%>
<br>
<br>
<%= link_to 'Back', cat_path(@cat)%>

app/views/cats/index.html.erb
<h1>Cats Index</h1>

<%if @agency%>
  <h4>Cats at <%=@agency.name%></h4>
  <%else%>
  <h4>All Cats</h4>
  <%end%>

  <% @cats.each do |c| %>
  <ul>
      <%=link_to c.name, agency_cat_path(c.agency, c)%> -
      <%=link_to c.agency.name, agency_path(c.agency)%> -
      <%=c.agency.state%>
      </ul>
  <%end%>

app/views/cats/new.html.erb
<% if @cat.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@cat.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @cat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Add a new cat!</h1>
<%= render 'form'%>
<br>
<br>
<%= link_to 'Back', cats_path%>

app/views/cats/show.html.erb
<h1><%=@cat.name%></h1>
<h4><%=link_to @cat.agency.name, agency_path(@cat.agency)%></h4>
<h4><%=@cat.sex%></h4>
<h4><%=@cat.age%> Years Old</h4>
<h4>Cat-itude: <%=@cat.disposition%></h4>
<h4>Spayed/Neutered? <%=@cat.neutered?%></h4>
<h4>Cost to Adopt: $<%=@cat.cost%></h4>

<br>

<% if current_user.admin? %>
<%= link_to "Edit Cat", edit_cat_path(@cat)%>
<%= link_to 'Delete',
             cat_path(@cat),
                         method: :delete,
                         data: { confirm: 'Are you sure?' } %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatCatalogue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <footer>
    <%if logged_in?%>
    <%=link_to 'Home', user_path(current_user)%>
    <%=link_to 'All Cats', cats_path%>
    <%=link_to 'All Adoption Agencies', agencies_path%>
    <%end%>
  </footer>
</html>

app/views/user/_form.html.erb
<% form_for(@user) do |f|%>

<%=f.label 'name'%> <br>
<%=f.text_field :name %> <br>

<%=f.label 'email'%> <br>
<%=f.text_field :email %> <br>

<%=f.label 'money'%> <br>
<%=f.text_field :money %> <br>

<%=f.label 'password'%> <br>
<%=f.password_field :password %> <br>

<%= f.label :admin, "Are you an Admin?" %>
<%= f.check_box :admin, class: "form-check-input" %><br>

<%= f.submit "Create User" %>
<%end%>

app/views/users/_form.html.erb
<h4> =^.^= </h4>
<%= form_for @user do |f|%>

<%=f.label 'name'%> <br>
<%=f.text_field :name %> <br>
<br>
<%=f.label 'email'%> <br>
<%=f.text_field :email %> <br>
<br>
<%=f.label 'money'%> <br>
$<%=f.text_field :money %> <br>
<br>
<%=f.label 'password'%> <br>
<%=f.password_field :password %> <br>
<br>
<%= f.label :admin, "Are you an Admin?" %>
<%= f.check_box :admin, class: "form-check-input" %><br>
<br>
<%= f.submit "Submit" %>
<%end%>
<br>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/users/new.html.erb
<h1> Sign Up! </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome <%=@user.name%></h1>
  <ul>
    <p><%=@user.email%>
    <p>$<%=@user.money%>
  </ul>

<p><%= link_to 'Edit User', edit_user_path(@user)%>
<p><%= link_to 'Log Out', signout_path%><p>

app/views/welcome/home.html.erb
<h1>Cat Adoption Center</h1>
<h3>Find your purr-fect friend!</h3>
<h4><%= link_to "Sign In", signin_path%></h4><br>
<h4><%= link_to('Log in with Facebook!', '/auth/facebook') %></h4>
<h4><%= link_to "Sign Up", new_user_path%></h4>